steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/bi-model-development/{Chloe_TestApp}:$SHORT_SHA', '.']
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/bi-model-development/{Chloe_TestApp}:$SHORT_SHA']
- name: 'gcr.io/cloud-builders/gcloud'
  args: ['beta', 'run', 'deploy', '{Chloe_TestApp}', '--region=us-central1', '--platform=managed', '--image=gcr.io/bi-model-development/{YOUR_NAME+App}:$SHORT_SHA']
timeout: 1200s