steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/bi-model-development/{chloe-shriya-uniswapapp}:$SHORT_SHA', '.']
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/bi-model-development/{chloe-shriya-uniswapapp}:$SHORT_SHA']
- name: 'gcr.io/cloud-builders/gcloud'
  args: ['beta', 'run', 'deploy', '{chloe-shriya-uniswapapp}', '--region=us-central1', '--platform=managed', '--image=gcr.io/bi-model-development/{chloe-shriya-uniswapapp}:$SHORT_SHA']
timeout: 1200s